version: "3"
services:
  postgres:
    image: postgres:latest
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: pg
    volumes:
      - postgres:/var/lib/postgresql/data2
volumes:
  postgres: ~